DROP TABLE IF EXISTS book;

CREATE TABLE book
(
    id BIGINT NOT NULL COMMENT 'ID',
    title VARCHAR(100) NULL DEFAULT NULL COMMENT 'book title',
    author VARCHAR(255) NULL DEFAULT NULL COMMENT 'book author',
    price DECIMAL(18, 8) NULL DEFAULT NULL COMMENT 'book price',
    type INT NULL DEFAULT NULL COMMENT '1-history; 2-education',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS shop_cart;

CREATE TABLE shop_cart
(
    id BIGINT NOT NULL COMMENT 'ID',
    book_id BIGINT NOT NULL COMMENT 'bookID',
    user_id VARCHAR(50) NULL DEFAULT NULL COMMENT 'userID',
    title VARCHAR(100) NULL DEFAULT NULL COMMENT 'book title',
    author VARCHAR(255) NULL DEFAULT NULL COMMENT 'book author',
    price DECIMAL(18, 8) NULL DEFAULT NULL COMMENT 'book price',
    qty DECIMAL(18, 4) NULL DEFAULT 0 COMMENT 'qty',
    amt DECIMAL(18, 4) NULL DEFAULT NULL COMMENT 'amt',
    type INT NULL DEFAULT NULL COMMENT '1-history; 2-education',
    PRIMARY KEY (id)
);