DROP TABLE IF EXISTS book;

CREATE TABLE book
(
    id BIGINT NOT NULL COMMENT '主键ID',
    title VARCHAR(100) NULL DEFAULT NULL COMMENT '标题',
    author VARCHAR(255) NULL DEFAULT NULL COMMENT '作者',
    price DECIMAL(18, 8) NULL DEFAULT NULL COMMENT '单价',
    type INT NULL DEFAULT NULL COMMENT '类型',
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS shop_cart;

CREATE TABLE shop_cart
(
    id BIGINT NOT NULL COMMENT '主键ID',
    book_id BIGINT NOT NULL COMMENT '书籍ID',
    user_id VARCHAR(50) NULL DEFAULT NULL COMMENT '用户ID',
    title VARCHAR(100) NULL DEFAULT NULL COMMENT '标题',
    author VARCHAR(255) NULL DEFAULT NULL COMMENT '作者',
    price DECIMAL(18, 8) NULL DEFAULT NULL COMMENT '单价',
    qty DECIMAL(18, 4) NULL DEFAULT 0 COMMENT '数量',
    amt DECIMAL(18, 4) NULL DEFAULT NULL COMMENT '总额',
    type INT NULL DEFAULT NULL COMMENT '类型',
    PRIMARY KEY (id)
);