# DataSource Config
spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: test
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql

# /api-docs config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
